---
- name: Upload Opsdash Agent
  synchronize: >
    src=opsdash-agent_{{ opsdash_agent_version }}_{{ opsdash_agent_architecture }}.deb
    dest="/tmp/opsdash.deb"
- name: Install Opsdash Agent
  apt: deb=/tmp/opsdash.deb

- name: Upload Opsdash Server
  synchronize: >
    src=opsdash-server_{{ opsdash_server_version }}_{{ opsdash_server_architecture }}.deb
    dest="/tmp/opsdash-server.deb"
  when: inventory_hostname == opsdash_server
- name: Install Opsdash Server
  apt: deb=/tmp/opsdash-server.deb
  when: inventory_hostname == opsdash_server
- name: Configure firewall for Opsdash (1/3)
  ufw: proto=tcp port=8080 rule=allow
  when: inventory_hostname == opsdash_server
- name: Configure firewall for Opsdash (2/3)
  ufw: proto=tcp port=6273 rule=allow
  when: inventory_hostname == opsdash_server
- name: Configure firewall for Opsdash (3/3)
  ufw: proto=udp port=6273 rule=allow
  when: inventory_hostname == opsdash_server

- name: Configure Opsdash server with license key
  copy: src={{ opsdash_license_filename }} dest=/etc/opsdash/license.lic
  when: inventory_hostname == opsdash_server
  notify: start opsdash server

- name: Point Agent to Opsdash Server
  lineinfile: >
    dest=/etc/opsdash/agent.cfg
    regexp=^server
    line=server\ =\ "{{ opsdash_server }}{{ fqdn }}"
  notify: start opsdash agent
